const fs = require('fs');

let data = fs.readFileSync('js/data.js', 'utf8');

const newBerserkerList = `    // --- BERSERKER CLASS LIST ---
    {
      id: "battle_cry",
      name: "Battle Cry",
      class: "Berserker",
      type: "Thunder",
      attunement: 1,
      cost: "3 Stamina",
      actTime: "Bonus Action",
      range: "Self (15 ft. radius)",
      components: "Sono",
      duration: "1 Round",
      description: "You let out a thunderous cry that steels the hearts of your allies. All allies within range gain +3 to damage rolls for attacks, spells, and abilities they make until the start of your next turn. In addition, they gain an Advantage die on saving throws against the Frightened condition for the same duration.",
      overchargeCost: "3 Stamina",
      overchargeDesc: "Increase the bonus to damage rolls by +3 and extend the duration by 2 rounds."
    },
    {
      id: "bellow",
      name: "Bellow",
      class: "Berserker",
      type: "Thunder",
      attunement: 2,
      cost: "4 Stamina",
      actTime: "Action",
      range: "Self (10 ft. radius)",
      components: "Sono",
      duration: "1 Round",
      description: "You unleash a primal, earth-shaking roar that unnerves nearby foes. All hostile creatures within 10 feet must succeed on a Wisdom saving throw (DC equal to 10 plus your Wisdom modifier). On a failed save, their movement speed is reduced by 5 times your Strength modifier feet (minimum 5 feet) until the start of your next turn.",
      overchargeCost: "4 Stamina",
      overchargeDesc: "The saving throw DC increases by +3, and the radius increases by 5 feet."
    },
    {
      id: "castigation",
      name: "Castigation",
      class: "Berserker",
      type: "Thunder",
      attunement: 1,
      cost: "3 Stamina",
      actTime: "1 Action",
      range: "30 Feet",
      components: "Sono",
      duration: "1 Round (Concentration)",
      description: "You unleash a voice of judgment and condemnation that strikes at the resolve of your foes. Choose a number of creatures within range equal to your Strength modifier (minimum 1). Each target must succeed on a Wisdom saving throw (DC equal to 8 plus your Strength modifier) or become Frightened for the duration. A creature can repeat the saving throw at the end of its turn. If it succeeds, it immediately ends the effect and gains immunity to Castigation for 1 minute.",
      overchargeCost: "3 Stamina",
      overchargeDesc: "The saving throw DC increases by +6."
    },
    {
      id: "disrupting_shout",
      name: "Disrupting Shout",
      class: "Berserker",
      type: "Thunder",
      attunement: 2,
      cost: "6 Stamina",
      actTime: "Action",
      range: "Self (15-foot radius)",
      components: "Sono",
      duration: "Instant",
      description: "Your shout carries raw force and command. Each hostile creature within range must make a Wisdom saving throw (DC equal to 10 plus your Strength modifier). On a failed save, the creature cannot take reactions until the start of its next turn.",
      overchargeCost: "6 Stamina",
      overchargeDesc: "Increase the radius by 5 feet, and the saving throw DC by +5."
    },
    {
      id: "execute",
      name: "Execute",
      class: "Berserker",
      type: "Physical",
      attunement: 1,
      cost: "3 Stamina",
      actTime: "Action",
      range: "Melee (Touch)",
      components: "Manus, Sono",
      duration: "Instant",
      description: "You deliver a brutal finishing strike against a weakened foe. This attack deals 1d4 Physical damage for every 25 Hit Points the creature is missing, up to a maximum number of dice equal to your Character level.",
      overchargeCost: "4 Stamina",
      overchargeDesc: "Each overcharge increases the step of the damage dice by up to d20."
    },
    {
      id: "fling",
      name: "Fling",
      class: "Berserker",
      type: "Physical",
      attunement: 2,
      cost: "5 Stamina",
      actTime: "Action",
      range: "Melee (Touch)",
      components: "Manus",
      duration: "Instant",
      description: "You seize a creature and hurl it through the air with brutal force. You may pick up and throw a willing creature that is Medium or smaller within your reach. Alternatively, you may attempt to grab a hostile creature of Medium size or smaller by winning a Strength contest against the target. On a success, you lift the creature and immediately throw it. Choose a direction and throw the creature up to 20 feet. The creature takes 1d6 Physical damage for every 10 feet traveled (up to 20d6), plus your Strength modifier when it lands. If the creature collides with a solid surface, object, or another creature, both creatures take the damage and fall prone.",
      overchargeCost: "3 Stamina",
      overchargeDesc: "Increase the maximum distance you can throw the creature by 10 feet each time you overcharge this ability."
    },
    {
      id: "fortify",
      name: "Fortify",
      class: "Berserker",
      type: "Physical",
      attunement: 1,
      cost: "2 Stamina",
      actTime: "Reaction",
      range: "Self",
      components: "None",
      duration: "Instant",
      description: "When you are hit by a melee or ranged Physical attack or ability, you may reduce the damage taken by an amount equal to your Constitution modifier. Damage cannot be reduced below 0.",
      overchargeCost: "2 Stamina",
      overchargeDesc: "Each time you overcharge this ability, the damage taken is reduced by an additional 1."
    },
    {
      id: "howl",
      name: "Howl",
      class: "Berserker",
      type: "Thunder",
      attunement: 2,
      cost: "5 Stamina",
      actTime: "Action",
      range: "Self (15 ft. radius)",
      components: "Sono",
      duration: "1 Round",
      description: "You release a primal, bone-rattling howl that saps the ferocity of your enemies. Each enemy within range must succeed on a Wisdom saving throw (DC equal to 10 plus your Strength modifier) or suffer -1 to all damage rolls until the start of your next turn.",
      overchargeCost: "3 Stamina",
      overchargeDesc: "Each time you overcharge this ability, increase the saving throw DC by 1 (up to 20), damage penalty by -1."
    },
    {
      id: "iron_skin",
      name: "Iron Skin",
      class: "Berserker",
      type: "Physical",
      attunement: 2,
      cost: "6 Stamina",
      actTime: "Action",
      range: "Self",
      components: "Manus, Sono",
      duration: "1 Round",
      description: "Your body hardens like living steel, transforming flesh into unyielding armor. Until the start of your next turn, you gain Defense equal to your Strength modifier.",
      overchargeCost: "3 Stamina",
      overchargeDesc: "Each time you overcharge this ability, increase the duration by 1 round and your Defense by +1."
    },
    {
      id: "leap",
      name: "Leap",
      class: "Berserker",
      type: "Physical",
      attunement: 2,
      cost: "5 Stamina",
      actTime: "Bonus Action",
      range: "Self",
      components: "None",
      duration: "Instant",
      description: "You convert momentum into devastating impact, hurling yourself across the battlefield. Leap up to 20 feet to an unoccupied space you can see. When you land, all creatures within 5 feet of your landing space must make a Dexterity saving throw (DC equal to 10 plus your Strength modifier). On a successful save, a creature takes half damage. On a failed save, a creature takes 1d6 bludgeoning damage (up to 20d6) for every 10 feet traveled during the leap, plus your Strength modifier.",
      overchargeCost: "4 Stamina",
      overchargeDesc: "Each time you overcharge this ability, increase the saving throw DC by 1 (up to 20) and the maximum distance you can leap by 10 feet."
    },
    {
      id: "pummel",
      name: "Pummel",
      class: "Berserker",
      type: "Physical",
      attunement: 2,
      cost: "6 Stamina",
      actTime: "Bonus Action",
      range: "Melee (Touch)",
      components: "Manus",
      duration: "1 Round",
      description: "You deliver a crushing blow that can overwhelm your opponent. The target must succeed on a Strength saving throw (DC equal to 10 plus your Strength modifier) or be stunned for 1 round.",
      overchargeCost: "6 Stamina",
      overchargeDesc: "Increase the saving throw DC by +4 and extend the stun duration by 2 rounds."
    },
    {
      id: "rallying_cry",
      name: "Rallying Cry",
      class: "Berserker",
      type: "Thunder",
      attunement: 1,
      cost: "2 Stamina",
      actTime: "Bonus Action",
      range: "Self (15-foot radius)",
      components: "Sono",
      duration: "1 Minute",
      description: "You call out to your allies with a voice of courage and resolve. All allies within range gain temporary hit points equal to 1d4 plus your Strength modifier for one minute.",
      overchargeCost: "2 Stamina",
      overchargeDesc: "Each time you overcharge this ability, the step of the dice rolled increases by up to d20."
    },
    {
      id: "scavenge",
      name: "Scavenge",
      class: "Berserker",
      type: "Physical",
      attunement: 1,
      cost: "2 Stamina",
      actTime: "Action",
      range: "Touch",
      components: "None",
      duration: "Instant",
      description: "You search a fallen creature for overlooked valuables, hidden gear, or forgotten resources. Target one corpse you are touching. Roll 1d20 plus your Luck modifier. The (DC equals the creature’s level times 2). On a success, you gain one additional loot opportunity from that corpse, as if it were searched with exceptional thoroughness. This may grant additional coin, consumable items, hidden equipment, or other appropriate treasure at the Game Master’s discretion. A corpse can only be successfully scavenged once using this ability.",
      overchargeCost: "0",
      overchargeDesc: ""
    },
    {
      id: "superstition",
      name: "Superstition",
      class: "Berserker",
      type: "Magic",
      attunement: 3,
      cost: "7 Stamina",
      actTime: "Reaction",
      range: "Self",
      components: "Manus, Sono, Reagent (Pinch of Salt)",
      duration: "1 Round",
      description: "You call upon instinct and primal distrust of unseen powers, hardening your spirit against divine influence. Until the end of your next turn, you gain resistance to Divine damage, including damage of the following types: Dark, Holy, Magic, and Nature.",
      overchargeCost: "3 Stamina",
      overchargeDesc: "Extend the duration by 2 rounds."
    },
    {
      id: "taunt",
      name: "Taunt",
      class: "Berserker",
      type: "Thunder",
      attunement: 2,
      cost: "4 Stamina",
      actTime: "Action",
      range: "Self (30-foot radius)",
      components: "Sono",
      duration: "1 Round",
      description: "You unleash a commanding challenge that compels your enemies to focus on you. Each enemy within range must make a Wisdom saving throw (DC equal to 10 plus your Strength modifier). On a failed save, a creature is compelled to target you until the end of your next turn. While compelled in this way: The creature must choose you as the target of its attacks if you are within its reach or range. If it cannot attack you, it must move toward you by the most direct safe route available. The creature may act normally if you are unreachable. On a successful save, the creature is unaffected.",
      overchargeCost: "4 Stamina",
      overchargeDesc: "Extend the duration by 2 rounds."
    },
    {
      id: "war_cry",
      name: "War Cry",
      class: "Berserker",
      type: "Thunder",
      attunement: 2,
      cost: "5 Stamina",
      actTime: "Action",
      range: "Self (15-foot radius)",
      components: "Sono",
      duration: "1 Round",
      description: "You release a thunderous battle cry that shakes the field. Each enemy within range must make a Wisdom saving throw (DC equal to 10 plus your Strength modifier). On a failed save, the creature has a disadvantage die on its damaging rolls.",
      overchargeCost: "4 Stamina",
      overchargeDesc: "Extend the duration by 2 rounds."
    },
    {
      id: "warpath",
      name: "Warpath",
      class: "Berserker",
      type: "Physical",
      attunement: 2,
      cost: "5 Stamina",
      actTime: "Action",
      range: "Self (10 ft Radius)",
      components: "Manus, Sono",
      duration: "Instant",
      description: "With a surge of strength, you violently shove aside those who stand between you and your prey. Choose one creature within your reach as your primary target. All other hostile creatures within 10 feet of you must succeed on a Strength saving throw (DC equal to 10 plus your Strength modifier) or be knocked back 10 feet directly away from you. A creature moved this way that collides with a solid surface, object, or another creature stops immediately and takes 1d6 (up to 20d6) Physical damage for every 10 feet of forced movement remaining. A creature struck this way must succeed on a Strength saving throw or also be knocked prone.",
      overchargeCost: "3 Stamina",
      overchargeDesc: "Increase the knockback distance by 10 feet each time you overcharge this ability."
    },
    {
      id: "weapon_throw",
      name: "Weapon Throw",
      class: "Berserker",
      type: "Physical",
      attunement: 2,
      cost: "4 Stamina",
      actTime: "Action",
      range: "10 ft",
      components: "Manus, Weapon",
      duration: "Instant",
      description: "With overwhelming strength, you hurl a weapon that would normally be impossible to throw. Choose a melee weapon you are holding and throw it in a straight line. The weapon deals 1d6 Physical damage for every 5 feet it travels. If the weapon strikes a creature, object, or surface before reaching its maximum distance, it still deals damage as though it had traveled the full distance.",
      overchargeCost: "2 Stamina",
      overchargeDesc: "Each time you overcharge this ability, increase the maximum throw distance by 5 feet."
    },
`;

const startIndex = data.indexOf('    // --- BERSERKER CLASS LIST ---');
const endIndex = data.indexOf('    // --- DISCIPLE CLASS LIST ---');

if (startIndex !== -1 && endIndex !== -1) {
  const newData = data.substring(0, startIndex) + newBerserkerList + data.substring(endIndex);
  fs.writeFileSync('js/data.js', newData, 'utf8');
  console.log('Success');
} else {
  console.log('Could not find markers');
}
