const fs = require('fs');
const path = 'C:/Users/rcmil/.gemini/antigravity/scratch/beasts-and-bounties/js/data.js';

const newItems = `
    { name: "Paper (Sheet)", cost: "1 Copper", weight: "0.02 lbs.", description: "A single sheet used for writing notes, messages, maps, or records.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Parchment (Sheet)", cost: "5 Copper", weight: "0.02 lbs.", description: "A durable writing material made from treated animal hide, favored for important documents and long-term records.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Sealing Wax", cost: "2 Silver Pieces (SP)", weight: "0.1 lbs.", description: "Colored wax used to seal letters, scrolls, and official documents.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Spellbook", cost: "10 Gold Pieces (GP)", weight: "5 lbs.", description: "A specialized book used by spellcasters to record magical formulas, rituals, and arcane notes.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Ball Bearings (1,000)", cost: "1 Gold Piece (GP)", weight: "2 lbs.", description: "Tiny metal spheres that can be scattered to create a slippery surface.", use: "As an action, you can spill these tiny metal balls to cover a 10 foot square area. A creature moving across the covered area must succeed on a Dexterity saving throw (DC equal to 10) or fall prone.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Block and Tackle", cost: "5 Gold Pieces (GP)", weight: "5 lbs.", description: "A pulley system used to lift or move heavy loads.", use: "When anchored, a block and tackle allows you to lift or drag up to four times the weight you could normally move and grant an advantage die on Strength checks made to lift or pull heavy objects.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Chain (10 ft.)", cost: "5 Gold Pieces (GP)", weight: "10 lbs.", description: "A heavy metal chain used for securing objects.", use: "Can secure doors, gates, prisoners, or objects. A chain can be wrapped around an object and locked with a lock.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Chalk (Piece)", cost: "1 Bronze Piece (BP)", weight: "0.1 lbs.", description: "A soft mineral used for writing or marking surfaces.", use: "Mark walls, floors, trails, or objects. Commonly used for navigation in dungeons and caves.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Hourglass", cost: "5 Gold Pieces (GP)", weight: "1 lb.", description: "A glass device that measures the passage of time using sand.", use: "Measures the passage of a fixed amount of time, typically one hour.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Lamp", cost: "5 Silver Pieces (SP)", weight: "1 lb.", description: "A small oil-burning lamp that provides light.", use: "Burns oil to provide bright light in a 15-foot radius and dim light for an additional 30 feet. One flask of oil fuels a lamp for 6 hours.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Lantern, Bullseye", cost: "10 Gold Pieces (GP)", weight: "2 lbs.", description: "A directional lantern that focuses light into a concentrated beam.", use: "Burns oil to provide bright light in a 15-foot cone and dim light for an additional 30 feet. One flask of oil fuels a lamp for 6 hours.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Lantern, Hooded", cost: "5 Gold Pieces (GP)", weight: "2 lbs.", description: "A lantern with adjustable shutters that allow the user to control light output.", use: "Burns oil to provide bright light in a 30-foot radius and dim light for an additional 30 feet. The hood can be closed to conceal the light. One flask of oil fuels the lantern for 6 hours.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Lock", cost: "5 Gold Pieces (GP)", weight: "1 lb.", description: "A metal locking mechanism used to secure containers, gates, or doors.", use: "Secure a door, chest, gate, or container. Requires thieves' tools or a key to open without damaging it.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Magnifying Glass", cost: "10 Gold Pieces (GP)", weight: "0.25 lbs.", description: "A lens used to enlarge small details and aid close inspection.", use: "Grants an advantage die on checks made to inspect small details. Can also be used to start a fire with sunlight, requiring several minutes of focused light.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Manacles", cost: "5 Gold Pieces (GP)", weight: "6 lbs.", description: "Metal restraints used to bind a creature's wrists.", use: "Restrain a creature's wrists. Escaping typically requires a successful Dexterity check, Strength check, or lockpicking attempt.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Mirror, Steel", cost: "1 Gold Piece (GP)", weight: "0.5 lbs.", description: "A polished steel mirror used for reflection and signaling.", use: "Observe around corners, inspect dangerous areas indirectly, signal allies with reflected light, or avoid looking directly at creatures with gaze attacks.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Oil (Flask)", cost: "1 Silver Piece (SP)", weight: "1 lb.", description: "A flask of lamp oil used as fuel for lanterns and lamps.", use: "Fuels lamps and lanterns for 6 hours. Can also be poured on the ground and ignited, creating a small area of fire that burns briefly and may damage creatures entering it.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Scale, Merchant's", cost: "5 Gold Pieces (GP)", weight: "3 lbs.", description: "A balance scale used to weigh goods, coins, and precious materials.", use: "Weigh goods, coins, gems, precious metals, and trade items to determine value or detect fraud.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Signal Whistle", cost: "2 Silver Pieces (SP)", weight: "0.1 lbs.", description: "A small whistle capable of producing loud, piercing signals.", use: "Produces a loud sound audible over long distances for communication, warnings, or signaling allies.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Spyglass", cost: "50 Gold Pieces (GP)", weight: "1 lb.", description: "A handheld telescope used to view distant objects.", use: "Magnifies distant objects, allowing detailed observation at long range.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Spikes, Iron (10)", cost: "1 Gold Piece (GP)", weight: "5 lbs.", description: "Ten iron spikes used to secure doors, reinforce structures, or anchor objects.", use: "Secure doors shut, reinforce structures, create climbing anchors, or pin ropes and equipment in place.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Vial", cost: "1 Silver Piece (SP)", weight: "0.1 lbs.", description: "A small glass container used to store liquids, powders, or reagents.", use: "Stores up to 4 ounces of liquid, powder, poison, alchemical substances, or spell components.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Whetstone", cost: "2 Silver Pieces (SP)", weight: "1 lb.", description: "A sharpening stone used to maintain the edge of blades and tools.", use: "Required to maintain and sharpen bladed weapons and tools. Necessary for certain Smithing, Leatherworking, or Outfitting tasks.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Divine Symbol (Amulet, Emblem, or Reliquary)", cost: "5 Gold Pieces (GP)", weight: "1 lb.", description: "A sacred object representing a deity, faith, or religious order. It is commonly used during worship, ceremonies, and divine spellcasting.", use: "A creature with a divine symbol can use it as a focus for divine magic and religious abilities. Made to perform rites, exorcisms, or religious ceremonies related to the wearer’s faith. Undead or abyssal creatures may react negatively to its presence at the GM’s discretion.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Divine Water (Flask)", cost: "2 Gold Pieces (GP)", weight: "1 lb.", description: "Water blessed by a religious figure and infused with sacred significance. It is often used in rituals, blessings, and purification rites.", use: "Can be splashed on a creature, object, or area. When used against undead or abyssal, the target must succeed on a Wisdom saving throw (DC equal to 12) or suffer a disadvantage die on its next roll. It can also be used to bless objects, purify corrupted water, or consecrate ground during rituals.", type: "Flask", slot: "Consumable" },
    { name: "Incense", cost: "5 Silver Pieces (SP)", weight: "0.1 lbs.", description: "A slow-burning blend of sacred resins, dried herbs, and consecrated oils prepared according to the rites of a faith or order. It is commonly burned during prayer, meditation, and religious ceremonies.", use: "When burned as part of a 10-minute ritual, incense enhances prayer, meditation, and divine rites. Creatures participating in the ritual gain an advantage die on Wisdom saving throws against fear or mental influence for 1 hour. It may also be required to perform certain religious ceremonies or commune with divine forces.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Bell", cost: "1 Gold Piece (GP)", weight: "0.5 lbs.", description: "A small handheld bell used to produce a clear ringing signal for attention, ceremony, or communication.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Jug or Pitcher", cost: "5 Silver Pieces (SP)", weight: "2 lbs.", description: "A simple container used to hold and pour liquids such as water, ale, or milk.", type: "Adventuring Gear", slot: "Container" },
    { name: "Perfume (Vial)", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A small vial of fragrant oils blended for personal scent or ceremonial use.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Signet Ring", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A ring engraved with a personal seal used to mark documents with identity or authority.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Soap", cost: "1 Silver Piece (SP)", weight: "0.5 lbs.", description: "A basic cleaning substance used for washing hands, clothing, and equipment.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Healer’s Kit", cost: "5 Gold Pieces (GP)", weight: "3 lbs.", description: "A compact set of bandages, salves, needles, and surgical tools used to stabilize wounds and treat injuries in the field.", type: "Adventuring Gear", slot: "Gear" },
    { name: "Health Potion", cost: "10 Gold Pieces (GP)", weight: "0.5 lbs.", description: "A restorative alchemical draught that mends wounds and restores vitality when consumed. Drinking it allows the user to immediately spend one Rest Die to restore hit points, adding their Constitution modifier to the result.", type: "Medicine", slot: "Consumable" },
    { name: "Stamina Potion", cost: "10 Gold Pieces (GP)", weight: "0.5 lbs.", description: "A fortifying alchemical mixture that restores physical vigor and endurance. Drinking it allows the user to immediately spend one Rest Die to restore stamina points, adding their Dexterity modifier to the result.", type: "Medicine", slot: "Consumable" },
    { name: "Mana Potion", cost: "10 Gold Pieces (GP)", weight: "0.5 lbs.", description: "A distilled arcane elixir that replenishes magical energy. Drinking it allows the user to immediately spend one Rest Die to restore mana points, adding their Intelligence modifier to the result.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Coagulation", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "An alchemical remedy that rapidly thickens blood and seals open wounds, removing the Bleed condition when consumed.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Antitoxin", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A purifying compound that neutralizes toxins within the body, removing the Poison condition when consumed.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Clarity", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A sharp tonic that clears vision and restores sight, removing the Blind condition when consumed.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Lucidity", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A stabilizing draught that restores mental control and dispels external influence, removing the Charm condition when consumed.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Audience", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A stimulating solution that restores hearing, removing the Deafen condition when consumed.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Pliability", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A flexible serum that restores muscle and nerve function, removing the Paralyze condition when consumed.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Articulation", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A throat-soothing elixir that restores speech, removing the Silence condition when consumed.", type: "Medicine", slot: "Consumable" },
    { name: "Vial of Mettle", cost: "5 Gold Pieces (GP)", weight: "0.1 lbs.", description: "A courage-steadying tonic that strengthens resolve, removing the Frighten condition when consumed.", type: "Medicine", slot: "Consumable" },
`;

let content = fs.readFileSync(path, 'utf8');

const targetStr = '{ name: "Ink Pen", cost: "1 Silver Piece (SP)", weight: "0.1 lbs.", description: "A simple writing instrument designed for use with bottled ink.", type: "Adventuring Gear", slot: "Gear" },\\n';

if (content.includes(targetStr)) {
    content = content.replace(targetStr, targetStr + newItems);
    fs.writeFileSync(path, content, 'utf8');
    console.log("SUCCESS: Replaced content correctly.");
} else {
    console.error("ERROR: Target string not found.");
}
